// Data source for media content
// Each item contains fields for video, audio, and image as requested.

export const ALL_MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const EVENT_TYPES = [
  "Fellowship Sunday",
  "Christmas Carol Competition",
  "Halleluyah Party",
  "Baby Dedication",
  "Weddings",
  "Queen Esther",
  "Grace",
  "Christmas Lights",
];

export const DEPARTMENTS = [
  "Children's Department",
  "Singles Department",
  "Works Department",
  "Publication Department",
  "Evangelism Department",
  "Holy Police",
  "Technical Crew",
  "Villa Sanitation",
  "Pastoral Care",
  "Missions Department",
  "Protocol Department",
  "Benevolence Department",
];

export const MEDIA_CATEGORIES = [
  "Church's Gallery",
  "Pastor's Gallery",
  ...DEPARTMENTS.map((d) => `${d} Gallery`),
];

export const mediaData = [
  {
    id: 1,
    title: "Sunday Service - Faith & Works",
    category: "Pastor's Gallery",
    type: "Fellowship Sunday",
    video: "https://www.youtube.com/watch?v=B9Loxo2SAV0",
    audio: null,
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg", // Specific image for this media
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-10-29",
    description:
      "A powerful sermon on faith and works delivered by Pastor John during our Sunday service.",
  },
  {
    id: 2,
    title: "Worship Night Highlights",
    category: "Church's Gallery",
    type: "Halleluyah Party",
    video: null,
    audio: "/audio.mp3",
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-10-22",
    description:
      "Experience the presence of God through our worship night highlights.",
  },
  {
    id: 3,
    title: "Community Outreach Gallery",
    category: "Benevolence Department Gallery",
    type: "Grace",
    video: null,
    audio: null,
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-10-15",
    description:
      "Photos from our recent community outreach program helping those in need.",
  },
  {
    id: 4,
    title: "Walking in Dominion",
    category: "Pastor's Gallery",
    type: "Fellowship Sunday",
    video: "https://www.youtube.com/watch?v=B9Loxo2SAV0",
    audio: null,
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-11-05",
    description: "Understanding our authority in Christ.",
  },
  {
    id: 5,
    title: "Youth Fire Conference",
    category: "Church's Gallery",
    type: "Fellowship Sunday",
    video: "https://www.youtube.com/watch?v=B9Loxo2SAV0",
    audio: "/audio.mp3",
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-09-15",
    description:
      "Highlights from the annual Youth Fire Conference. Igniting a generation for Jesus.",
  },
  {
    id: 6,
    title: "Men's Breakfast Fellowship",
    category: "Church's Gallery",
    type: "Fellowship Sunday",
    video: null,
    audio: "/audio.mp3",
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-08-20",
    description:
      "A time of bonding, prayer, and the word for the men of the house.",
  },
  {
    id: 7,
    title: "Women of Virtue Seminar",
    category: "Singles Department Gallery",
    type: "Queen Esther",
    video: "https://www.youtube.com/watch?v=B9Loxo2SAV0",
    audio: null,
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-07-10",
    description:
      "Empowering women to walk in their God-given purpose and identity.",
  },
  {
    id: 8,
    title: "Choir Ministration - Hallelujah",
    category: "Church's Gallery",
    type: "Christmas Carol Competition",
    video: "https://www.youtube.com/watch?v=B9Loxo2SAV0",
    audio: "/audio.mp3",
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-11-12",
    description: "A soul-lifting ministration by the church choir.",
  },
  {
    id: 9,
    title: "Children's Bible Quiz",
    category: "Children's Department Gallery",
    type: "Baby Dedication",
    video: null,
    audio: null,
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-06-01",
    description: "Our children displaying their knowledge of the scriptures.",
  },
  {
    id: 10,
    title: "Mid-Year Thanksgiving",
    category: "Church's Gallery",
    type: "Fellowship Sunday",
    video: "https://www.youtube.com/watch?v=B9Loxo2SAV0",
    audio: "/audio.mp3",
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-06-30",
    description:
      "Giving thanks to God for His faithfulness through the first half of the year.",
  },
  {
    id: 11,
    title: "Understanding Grace",
    category: "Pastor's Gallery",
    type: "Grace",
    video: null,
    audio: "/audio.mp3",
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-05-15",
    description: "A deep dive into the concept of Grace in the New Testament.",
  },
  {
    id: 12,
    title: "Prayer Marathon 2023",
    category: "Pastoral Care Gallery",
    type: "Fellowship Sunday",
    video: "https://www.youtube.com/watch?v=B9Loxo2SAV0",
    audio: null,
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-04-10",
    description: "12 hours of non-stop prayer and intercession for our nation.",
  },
  {
    id: 13,
    title: "Ushering Department Training",
    category: "Protocol Department Gallery",
    type: "Fellowship Sunday",
    video: null,
    audio: null,
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-03-05",
    description: "Equipping our ushers for excellence in service.",
  },
  {
    id: 14,
    title: "Christmas Carol Service",
    category: "Church's Gallery",
    type: "Christmas Carol Competition",
    video: "https://www.youtube.com/watch?v=B9Loxo2SAV0",
    audio: "/audio.mp3",
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-12-24",
    description: "Celebrating the birth of our Savior with carols and lessons.",
  },
  {
    id: 15,
    title: "Technical Team Workshop",
    category: "Technical Crew Gallery",
    type: "Fellowship Sunday",
    video: null,
    audio: null,
    image: "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    images: [
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
      "https://img.youtube.com/vi/B9Loxo2SAV0/maxresdefault.jpg",
    ],
    date: "2023-02-15",
    description: "Training session for the media and technical team.",
  },
];
